config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "ingredients#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  resources :ingredients do
    collection do
      get :fridgy
    end
  end
  get "/set_meal_type", to: "ingredients#set_meal_type"
  get "/set_category", to: "ingredients#set_category"
  resources :recipes, only: [:index, :show, :create, :edit, :update] do
    member do
      get :favourite
    end
  end
  get "/list_favourites", to: "recipes#list_favourites"
  get "/loading_page", to: "recipes#loading"
  get "/status/:job_id", to: "recipes#job_status"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :user
  has_many :ingredient_recipe, dependent: :destroy
  has_many :recipe, through: :ingredient_recipe, dependent: :destroy
  validates :name, :amount, :measurement, presence: true

  MEASUREMENTS = ['ml', 'l', 'g', 'kg', 'tsp', 'tbsp', 'piece']
  MEAL_TYPES = ['Breakfast', 'Lunch', 'Dinner']
  CATEGORIES = ['Balkan', 'French', 'Indian', 'Italian', 'Japanese', 'Korean', 'American', 'LatinAmerican', 'Pakistani', 'Spanish', 'Thai', 'Vietnamese']

end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
require "open-uri"
class Recipe < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :ingredient_recipes, dependent: :destroy
  has_many :ingredients, through: :ingredient_recipes, dependent: :destroy
  validates :category, :meal_type, presence: true

  include PgSearch::Model
    pg_search_scope :search_by_title_and_content,
    against: [ :title, :content ],
     using: {
      tsearch: { prefix: true }
  }

  after_save if: -> { saved_change_to_title? || saved_change_to_content? } do
   set_photo
  end

  private

  def set_photo
    client = OpenAI::Client.new
    response = client.images.generate(parameters: {
     prompt: "A recipe image of #{title}", size: "256x256"
    })

    url = response["data"][0]["url"]
    file =  URI.open(url)

    photo.purge if photo.attached?
    photo.attach(io: file, filename: "ai_generated_image.jpg", content_type: "image/png")
    return photo
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :ingredients, dependent: :destroy
  has_many :recipes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = current_user.ingredients.order(name: :asc)
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.user = current_user


    if @ingredient.save
      if params[:fridgy].present?
        redirect_to fridgy_ingredients_path
      else
        redirect_to root_path
      end
    end
  end

  def set_meal_type
    session[:ingredients_ids] = params[:ingredients_ids] if params[:ingredients_ids]
  end

  def set_category
    session[:meal_type] = params[:meal_types] if params[:meal_types]
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to fridgy_ingredients_path
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update(ingredient_params)
    redirect_to fridgy_ingredients_path, notice: 'Ingredient was successfully updated.'
  end

  def fridgy
    @ingredients = current_user.ingredients.order(name: :asc)
    @ingredient = Ingredient.new
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name, :amount, :measurement)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes.last(3)
  end

  def create
    session[:category] = params[:category] if params[:category]
    # Find ingredients based on [session ingredient_ids]
    ingredient_ids = session[:ingredients_ids]
    meal_type = session[:meal_type]
    category = session[:category]
    #=> #<GlobalID:0x000055988bc4dd20 [...] gid://background-jobs-demo/User/1>>
    serialized_user = current_user.to_global_id.to_s
    job =  AiRecipeGeneratorJob.perform_later(ingredient_ids, meal_type, category, serialized_user)
    @job_id = job.provider_job_id

      # we need to create one ingredient recipe for each ingredient
    redirect_to loading_page_path(job_id: @job_id)
  end

  def loading
    @job_id =  params[:job_id] if params[:job_id].present?

  end

  def job_status
    @job_id =  params[:job_id] if params[:job_id].present?
    status = Sidekiq::Status::status(@job_id)
    progress = Sidekiq::Status::pct_complete @job_id
    render json: {status: status, progress: progress}
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def favourite
    @recipe = Recipe.find(params[:id])
    @recipe.update(favourite: !@recipe.favourite)
    @recipe.save
    redirect_to recipe_path(@recipe)
  end

  def list_favourites
    @recipes = current_user.recipes.where(favourite: true)
    if params[:query].present?
      @recipes = @recipes.where("title ILIKE ?", "%#{params[:query]}%")
    end
  end

  def delete
    @recipe = Recipe.destroy(params[:id])
    redirect_to @recipes
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :content, :meal_type, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
  content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

 def meta_description
 content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
 end

 def meta_image
 meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
 # little twist to make it work equally with an asset or a url
 meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
 end
 end

app/views/ingredients/fridgy.html.erb
<div class="header">
  <h2>Your Fridgy, Your Way</h2>
  <p>Keep track of what you have in stock.</p>
</div>
<div class="container justify-content-center col-12 col-lg-6">
  <div style="max-height: 200px; overflow-y: auto;">
    <table style="width: 100%; margin-bottom: 20px;">
      <thead>
        <tr>
          <th>Name</th>
          <th>Amount</th>
          <th>Unit</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @ingredients.each do |ingredient| %>
          <tr>
            <td><%= ingredient.name %></td>
            <td><%= ingredient.amount %></td>
            <td><%= ingredient.measurement %></td>
            <td>
              <p data-bs-toggle="modal" data-bs-target="<%= "#ingredient-#{ingredient.id}" %>">
                <i id="edit-ingredient" class="fa-regular fa-pen-to-square"></i>
              </p>
            </td>
            <td>
              <%= link_to ingredient_path(ingredient), data: { turbo_method: :delete, turbo_confirm: "Are you sure you would like to delete #{ingredient.name}?" }, class: "delete" do %>
                <i id="delete-ingredient" class="fa-regular fa-trash-can"></i>
              <% end %>
            </td>
          </tr>
          <%# Modal for editing ingredient %>
        <% end %>
      </tbody>
    </table>

    <% @ingredients.each do |ingredient| %>
      <div class="modal fade" id="ingredient-<%= ingredient.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Edit <%= ingredient.name %></h5>
            </div>
            <div class="modal-body">
              <%= simple_form_for ingredient do |f| %>
                <%= f.input :name %>
                <%= f.input :measurement, collection: Ingredient::MEASUREMENTS %>
                <%= f.input :amount, as: :numeric, input_html: { min: '0', step: 'any', class: 'custom-placeholder' } %>
                <%= f.submit %>
              <% end %>
            </div>
          </div>
        </div>
    </div>
  <% end %>
  </div>
</div>
<div style="margin-top: 30px;">
  <%= simple_form_for(@ingredient) do |f| %>
    <%= hidden_field_tag :fridgy, true%>
    <div class="align-box">
      <h3>New ingredient:</h3>
      <div class="container-input">
        <div class="w-100">
          <%= f.input :name, placeholder: "e.g. Milk", label: false,  input_html: { class: 'custom-placeholder' } %>
        </div>
      </div>
    </div>
    <div class="align-box">
      <h3>Select measurement:</h3>
      <div class="container-input">
        <div class="w-100">
          <%= f.input :measurement, placeholder: "Please select", collection: Ingredient::MEASUREMENTS, label: false, input_html: { class: 'custom-placeholder' }%>
        </div>
      </div>
    </div>
    <div class="align-box">
      <h3>Amount:</h3>
      <div class="container-input">
        <div class="w-100">
          <%= f.input  :amount, placeholder: "e.g. 1, 2, 3, etc.", label: false, as: :numeric, input_html: { min: '0', step: 'any' }, input_html: { class: 'custom-placeholder' }  %>
        </div>
      </div>
    </div>
    <!--button-->
    <div class="align-box">
      <%= f.submit "Add to your Fridgy", class:"submit-button", style:"width: 300px"%>
    <% end %>
  </div>
</div>

app/views/ingredients/index.html.erb
<div class="user-style-section">
  <!-- user section -->
  <div class="user-info">
    <img src='https://cdn-icons-png.freepik.com/512/10542/10542498.png' class="avatar-large" />
    <div class="user-info-text">
      <h1>Hi <%= current_user.name %>,</h1>
      <p>Welcome to your Fridgy!</p>
    </div>
  </div>
  <!-- Delete Button -->
  <div class="trash-bin">
    <%= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "delete-icon" do %>
      <i class="fi fi-rr-leave"></i>
    <% end %>
  </div>
</div>
<!-- This is the add new ingredient section -->
<div class="center">
  <%= simple_form_for(@ingredient) do |f| %>
    <div class="align-box">
      <h3>New ingredient:</h3>
      <div class="container-input">
        <div class="w-100">
          <%= f.input :name, placeholder: "e.g. Milk", label: false,  input_html: { class: 'custom-placeholder' } %>
        </div>
      </div>
    </div>
    <div class="align-box">
      <h3>Select measurement:</h3>
      <div class="container-input">
        <div class="w-100">
          <%= f.input :measurement, placeholder: "Please select", collection: Ingredient::MEASUREMENTS, label: false, input_html: { class: 'custom-placeholder' } %>
        </div>
      </div>
    </div>
    <div class="align-box">
      <h3>Amount:</h3>
      <div class="container-input">
        <div class="w-100">
          <%= f.input  :amount, placeholder: "e.g. 1, 2, 3, etc.", label: false, as: :numeric, input_html: { min: '0', step: 'any' }, input_html: { class: 'custom-placeholder' }  %>
        </div>
      </div>
    </div>
    <!--button-->
    <div class="align-box">
      <%= f.submit "Add to your Fridgy", class:"submit-button", style:"width: 300px"%>
    <% end %>
    <!-- select ingredients section -->
    <%= form_with url: "/set_meal_type", method: :get do |f| %>
      <h2 style="margin-bottom: 30px;">Choose your ingredients:</h2>
      <div style="max-height: 200px; overflow-y: auto;">
        <div class="ingredient-checkbox">
          <% @ingredients.each do |ingredient| %>
            <div>
              <%= check_box_tag 'ingredients_ids[]', ingredient.id %>
              <%= ingredient.name %>
            </div>
          <% end %>
        </div>
      </div>
      <%= f.submit "Let's Cook!", class:"submit-button-btn", style:"width: 300px"%>
    <% end %>
  </div>
</div>

app/views/ingredients/set_category.html.erb
<div class="container">
<h1 class="headline">Choose your cuisine</h1>

<%= form_with url: recipes_path, method: :post do |f| %>
  <div class="button-group">
    <% Ingredient::CATEGORIES.each do |category| %>
      <div class="button-wrapper">
        <%= radio_button_tag 'category', category, false, id: category %>
        <%= label_tag category, category, class: 'button-label' %>
      </div>
    <% end %>
    <%= f.submit 'Generate Recipe', class: 'submit-button-label' %>
  </div>
<% end %>
</div>

app/views/ingredients/set_meal_type.html.erb
  <h2 class="headline">Select your meal type</h2>

  <%= simple_form_for :meal_types, url: "/set_category", method: :get do |f| %>
    <div class="category-wrapper">
      <% ['Breakfast', 'Lunch', 'Dinner'].each do |meal_type| %>
        <div class="category-item">
          <%= image_tag "#{meal_type.downcase}-black.png", class: "meal-type-icon" %>
          <label class="category-label">
            <%= f.radio_button :meal_type, meal_type, class: 'category-selector', id: meal_type.downcase %>
            <%= meal_type %>
          </label>
        </div>
      <% end %>
    </div>
    <%= f.submit "Choose the Category", class: "submit-button-thu" %>
  <% end %>

  <script>
    document.addEventListener('DOMContentLoaded', (event) => {
      const categoryItems = document.querySelectorAll('.category-item');
      const radioButtons = document.querySelectorAll('.category-selector');

      categoryItems.forEach(item => {
        item.addEventListener('click', () => {
          categoryItems.forEach(i => i.classList.remove('selected'));
          item.classList.add('selected');
          item.querySelector('.category-selector').checked = true;
        });
      });

      radioButtons.forEach(radio => {
        radio.addEventListener('change', (event) => {
          categoryItems.forEach(item => item.classList.remove('selected'));
          event.target.closest('.category-item').classList.add('selected');
        });
      });
    });
  </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fridgy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.4.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>
    <link rel='stylesheet' href='https://cdn-uicons.flaticon.com/2.4.0/uicons-solid-rounded/css/uicons-solid-rounded.css'>
    <%= javascript_importmap_tags %>
    <!-- Font Poppins -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <!-- Font josefin-sans -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <%# <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png"> %>
    <%# <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"> %>
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
    <!-- pwa -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%=favicon_link_tag("favicon.ico") %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
  </head>
  <body><%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= render 'shared/ios_pwa_links' %>
    <%= yield %>
    <div class="buffer" style="height: 70px;"></div>
  </body>
</html>

app/views/pages/home.html.erb
<!-- user section -->

<div class="user-info">
  <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/Avatar_icon_green.svg/2048px-Avatar_icon_green.svg.png' class="avatar-large" />
  <div class="user-info-text">
    <h1>Hi <%= current_user.name %>,</h1>
    <p>Welcome to your Fridgy</p>
  </div>
</div>

<!-- This is the add new ingredient section -->
<div class="container">
  <h1>Add a ingredient</h1>

  <%= simple_form_for(@ingredient) do |f| %>
    <div class="row">
      <div class="col-6">
        <%= f.input :name, placeholder: 'your Ingredient', label: false, input_html: { class: 'custom-placeholder' } %>
      </div>
      <div class="col-3">
        <%= f.input :measurement, collection: Ingredient::MEASUREMENTS, placeholder: 'Measurement', label: false, input_html: { class: 'custom-placeholder' } %>
      </div>
      <div class="col-3">
        <%= f.input  :amount, label: false, as: :numeric, input_html: { min: '0', step: 'any' }, input_html: { class: 'custom-placeholder' }  %>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <%= f.submit "Add your Ingredient", class:"btn btn-primary"%>
      </div>
    </div>
  <% end %>
</div>

<!-- display ingredients-list -->

<% @ingredients.each do |ingredient| %>
  <%= ingredient.name %>
<%end %>

<%= form_with url: "/set_meal_type", method: :get do |f| %>
<% @ingredients.each do |ingredient| %>
  <%= check_box_tag 'ingredients_ids[]', ingredient.id %>
  <%= ingredient.name %>
  <% end %>
  <%= f.submit "Choose the Meal_type" %>
<% end %>

<!-- select meal type section -->

<h2>Select the meal you want to cook</h2>
<div class="meal-cards">
  <div class="card">
    <img src="path/to/breakfast.jpg" alt="Breakfast" class="card-image">
    <div class="card-text">Breakfast</div>
  </div>
  <div class="card">
    <img src="path/to/lunch.jpg" alt="Lunch" class="card-image">
    <div class="card-text">Lunch</div>
  </div>
  <div class="card">
    <img src="path/to/dinner.jpg" alt="Dinner" class="card-image">
    <div class="card-text">Dinner</div>
  </div>
</div>

<!-- Ingredients with search section -->

<%= simple_form_for :search, url: root_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" placeholder='search ingredients'  />
    <div class="button-wrap">
      <button name="button" type="submit" class="btn btn-flat mr-3">
        <i class="fas fa-search"></i>
      </button>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<p><%= recipe.content %></p>
<%= cl_image_tag recipe.photo.key, alt: "AI-generated image of the recipe" if recipe.photo.attached? %>

app/views/recipes/index.html.erb
<h2 style="margin-top: 50px; font-size: 25px"">Choose one of these recipes:</h1>
<div class="suggested-recipes">
  <% @recipes.each do |recipe| %>
    <div class=''>
      <%= link_to recipe_path(recipe) do  %>
        <div class="recipe-wrapper">
          <% if recipe.photo.attached? %>
            <%= cl_image_tag recipe.photo.key, class: "recipe-image"%>
          <% else %>
            <%= image_tag "food_placeholder.jpeg", class: "recipe-image" %>
          <% end %>
          <div class="recipe-text">
            <h2><%= recipe.title %></h2>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/recipes/list_favourites.html.erb
<h2 style="margin-top: 50px; font-size: 25px; margin-bottom: 30px">Favorite Recipes</h2>
<div class="container">
  <div class="row justify-content-center my-3">
    <div class="col-12 col-md-8 col-lg-6">
      <%= form_with url: list_favourites_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "d-flex input", placeholder: "Type a keyword of a recipe" %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary btn-search" %>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center">
    <% @recipes.each do |recipe| %>
      <div class="center">
        <%= link_to recipe_path(recipe), class: 'card-link' do %>
          <div class="card">
            <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= recipe.photo.attached? ? cl_image_path(recipe.photo.key) : asset_path('food_placeholder.jpg') %>);">
              <span><%= recipe.title %></span>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/loading.html.erb
<video muted="" loop="" playsinline="" autoplay="" data-src="https://cdn.dribbble.com/users/1998175/screenshots/7184429/media/24ccc58b8b30005fc48ca8343f95e612.mp4" data-video-small="https://cdn.dribbble.com/users/1998175/screenshots/7184429/media/d4ac10e83012fd9a53f3ec969ebb1f84.mp4"
data-video-medium="https://cdn.dribbble.com/users/1998175/screenshots/7184429/media/61f489854e9699e4f6d86b4b6f4244c5.mp4"
data-video-large="https://cdn.dribbble.com/users/1998175/screenshots/7184429/media/24ccc58b8b30005fc48ca8343f95e612.mp4" src="https://cdn.dribbble.com/users/1998175/screenshots/7184429/media/61f489854e9699e4f6d86b4b6f4244c5.mp4"
class="animation"></video>

<div class="container" data-controller= "job-status" data-job-status-job-id-value = "<%= @job_id %>">
  <div class="progress">
    <div class="progress-bar" data-job-status-target="bar" role="progressbar" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100" style="margin-top 50px">0%</div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="recipe-header">
  <% if @recipe.photo.attached? %>
    <%= cl_image_tag @recipe.photo.key, class: "recipe-image"%>
  <% else %>
    <%= image_tag "food_placeholder.jpg", class: "recipe-image" %>
  <% end %>
  <br>
  <div class="favorite-icons">
    <% if @recipe.favourite? %>
    <%= link_to favourite_recipe_path(@recipe), style: "text-decoration: none;" do %>
      <i id="favorite-icon" class="fi fi-sr-star"></i>
    <% end %>
  <% else %>
    <%= link_to favourite_recipe_path(@recipe), style: "text-decoration: none;" do %>
      <i id="unfavorite-icon" class="fi-rr-star"></i>
    <% end %>
  <% end %>
  </div>
  <h2><%= @recipe.title %></h2>
  <h3>Did you like this recipe? Click on the star above!</h4>
</div>
<div class="recipe-body">
  <% @recipe.content.split(/\s?\d\.\s/).reject{|c|c.empty?}.each_with_index do |line, index| %>
    <%= "#{index + 1}. #{line.strip}\n" %>
    <br>
    <br>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <%= link_to root_path, class: "#{params[:action] == 'index' ? 'active' : ''}" do %>
    <i class="fi-rr-home"></i>
  <% end %>

  <%= link_to "/ingredients/fridgy", class: "#{params[:action] == 'fridgy' ? 'active' : ''}" do %>
    <i class="fi-rr-refrigerator"></i>
  <% end %>

  <%= link_to list_favourites_path, class: "#{params[:action] == 'list_favourites' ? 'active' : ''}"  do %>
    <i class="fi-rr-star"></i>
  <% end %>
</div>